language: node_js
node_js:
  - "10"
dist: dist
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  # - npm run test-headless
  # - ng build --prod --base-href https://t-palmer.github.io/travis-demo/
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "grigoreme"
    - git config --local user.email "grigore997@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $FILE_UPLOAD
  skip_cleanup: $SKIP_CLEANUP
  on:
    branch: master