language: node_js
node_js:
  - '10'
dist: dist
sudo: required
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - npm install
    - npm run test
    - npm run build
    - node demo/local
script:
  - npm run tslint
  # - npm run test-headless
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "grigoreme"
  - git config --local user.email "grigore997@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: $SKIP_CLEANUP
addons:
  apt:
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - build-essential
      - g++
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/